name: msi_clock
description: "Metro Staff Inc. Time Clock Application"
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Camera and Storage
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  image_picker: ^1.0.7

  # Network
  http: ^1.2.1
  connectivity_plus: ^5.0.2

  # State Management
  provider: ^6.1.2

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  xml: ^6.5.0
  google_fonts: ^6.1.0
  wakelock_plus: ^1.1.4
  package_info_plus: ^4.2.0 # For app version information
  url_launcher: ^6.1.14 # For opening APK download URL
  dio: ^5.4.0 # For downloading files
  permission_handler: ^11.0.1 # For install permission
  battery_plus: ^4.0.0 # For accessing battery information
  network_info_plus: ^4.0.0 # For getting device MAC address
  screen_brightness: ^1.0.0 # For controlling screen brightness
  crypto: ^3.0.3 # For HMAC-SHA256 signing (R2 uploads)
  disk_space_plus: ^0.2.6 # For getting device storage information

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
